config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :blogs

  resources :types

  resources :dimensions

  resources :boards

  resources :contacts

  devise_for :users
  get 'pages/home'
  get 'pages/diamond'
    get 'pages/showusers'
  root 'pages#home'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
   has_attached_file :image, :styles => { :medium => "680x600>", :thumb => "350x309>" }
  #  validates :image, presence: true
   validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }
   include Bootsy::Container

end

app/models/board.rb
class Board < ActiveRecord::Base
	  		has_attached_file :logo, :styles => { :medium => "150x150>", :thumb => "75x75>" }
	  		has_attached_file :waveheightlogo, :styles => { :medium => "200x128>", :thumb => "100x64>" }
	  		has_attached_file :rockerlogo, :styles => { :medium => "400x94>", :thumb => "128x30>" }
	  	  has_attached_file :skilllogo, :styles => { :medium => "400x94>", :thumb => "128x30>" }
	  		has_attached_file :image, :styles => { :medium => "400x502>", :thumb => "250x314>" }
	  		has_attached_file :triimage, :styles => { :medium => "483x612>", :thumb => "200x253>" }
        validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }
        has_many :dimensions
        belongs_to :type
        
end

app/models/contact.rb
class Contact < ActiveRecord::Base


private



end

app/models/dimension.rb
class Dimension < ActiveRecord::Base

	belongs_to :board
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :boards
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @blogs = Blog.all.order(created_at: :desc)
    respond_with(@blogs)
  end

  def show
    respond_with(@blog)
  end

  def new
    @blog = Blog.new
    respond_with(@blog)
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.save
    respond_with(@blog)
  end

  def update
    @blog.update(blog_params)
    respond_with(@blog)
  end

  def destroy
    @blog.destroy
    respond_with(@blog)
  end

  private
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :body, :image, :video)
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    @boards = Board.all.order("board_name ASC")
    @types = Type.all
    respond_with(@boards)
  end

  def show
    @boards = Board.all.order("board_name ASC")
    @dimension = Dimension.new
    respond_with(@board)
  end

  def new
    @board = Board.new
    @types = Type.all
    respond_with(@board)
  end

  def edit
        @types = Type.all
  end

  def create
    @board = Board.new(board_params)
    @board.save
    respond_with(@board)
  end

  def update
    @board.update(board_params)
    respond_with(@board)
  end

  def destroy
    @board.destroy
    respond_with(@board)
  end

  private
    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:board_name, :type_id, :category, :board_description, :image, :triimage, :logo, :waveheightlogo, :rockerlogo, :skilllogo)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]


  respond_to :html

  def index
    @contacts = Contact.all
    respond_with(@contacts)
  end

  def show
    respond_with(@contact)
  end

  def new
    @contact = Contact.new
    respond_with(@contact)
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.save
    UserMailer.welcome_email(@contact).deliver
    respond_with(@contact)
  end



  def update
    @contact.update(contact_params)
    respond_with(@contact)
  end

  def destroy
    @contact.destroy
    respond_with(@contact)
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:contact_name, :contact_email, :contact_phone, :contact_help, :contact_notes, :contact_status)
    end
end

app/controllers/dimensions_controller.rb
class DimensionsController < ApplicationController
  before_action :set_dimension, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    @dimensions = Dimension.all
    @boards = Board.all
    respond_with(@dimensions)
  end

  def show
    respond_with(@dimension)
  end

  def new
    @dimension = Dimension.new
    @boards = Board.all
    respond_with(@dimension)
  end

  def edit
      @boards = Board.all
  end

  def create
    @dimension = Dimension.new(dimension_params)
    @dimension.save
    respond_with(@dimension)
  end

  def update
    @dimension.update(dimension_params)
    respond_with(@dimension)
  end

  def destroy
    @dimension.destroy
    respond_with(@dimension)
  end

  private
    def set_dimension
      @dimension = Dimension.find(params[:id])
    end

    def dimension_params
      params.require(:dimension).permit(:length, :width, :thickness, :board_id, :volume)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
   def diamond
  end
  def showusers
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @types = Type.all
    @boards = Board.all
    respond_with(@types)
  end

  def show
    respond_with(@type)
  end

  def new
    @type = Type.new
    respond_with(@type)
  end

  def edit
  end

  def create
    @type = Type.new(type_params)
    @type.save
    respond_with(@type)
  end

  def update
    @type.update(type_params)
    respond_with(@type)
  end

  def destroy
    @type.destroy
    respond_with(@type)
  end

  private
    def set_type
      @type = Type.find(params[:id])
    end

    def type_params
      params.require(:type).permit(:type_name, :type_description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dimensions_helper.rb
module DimensionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

    <%= f.label :body %><br>
    <%= f.bootsy_area :body, :cols => 100, :rows => 20 %>

    <div class="field">
      <%= f.label :video %><br>
      <%= f.text_field :video %>
    </div>



  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<% if user_signed_in? %>
<%= link_to 'Create New Post', new_blog_path, class: "btn btn-default" %>
<br /><br />
<% end %>
<!-- Section -->
<section class="page-section">
    <div class="container relative">
                <div class="row masonry">
                    <% @blogs.each do |blog| %>
                    <!-- Post Item -->
                    <div class="col-sm-6 col-md-4 col-lg-4 mb-60 mb-xs-40">
                      <div class="post-prev-title font-alt">
                        <h4><%= blog.title %></h4>
                      </div>
                        <div class="post-prev-img">
                            <% if blog.image.present? %>
                            <%= image_tag blog.image.url(:thumb) %>
                            <% else %>
                            <%= raw(blog.video) %>
                            <% end %>
                        </div>
                        <div class="post-prev-text">
                    <p>
                      <%= raw(blog.body.truncate(300)) %>
                    </p>
                        </div>
                        <div class="post-prev-more">
                          <i class="fa fa-calendar-o"></i> &nbsp;
                              <i><%= blog.created_at.to_formatted_s(:short) %></i>
                              <% if user_signed_in? %>
                              <br />
                              <%= link_to 'Show', blog %>
                              <%= link_to 'Edit', edit_blog_path(blog) %>
                              <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
                              <% end %>
                        </div>

                    </div>
                    <!-- End Post Item -->
                    <% end %>


                </div>



    </div>
</section>
<!-- End Section -->


<!-- Divider -->
<hr class="mt-0 mb-0"/>
<!-- End Divider -->

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<p>
  <strong>Video</strong>
  <%= raw(@blog.video) %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<h1>SURFBOARDS</h1>
<div class="row">
<div class="col-md-12" id="spacer"></div><!-- end md 4 -->
</div><!-- end row -->
<br />

<% if user_signed_in? %>
<%= link_to 'Add a New Board', new_board_path, class: "btn btn-default" %> <br /> <br />
<% end %>


<div class="row">
  <div class="col-md-12">
                  &nbsp; &nbsp; &nbsp; <%= link_to "> Sort By Board Type", types_path %>
  </div>


<div class="row">
					<div class="col-md-12">
									<% @boards.each do |board| %>
															<div class="listing">
																		<center>
																		<b><%= link_to board.board_name, board %></b><br />
																					<%= link_to image_tag(board.image.url(:medium), class: "img-responsive"), board %><br />
																									<% if user_signed_in? %>
																				   <%= link_to 'View', board %> &nbsp; &nbsp; <%= link_to 'Edit', edit_board_path(board) %>&nbsp; &nbsp;
																				     <%= link_to 'Delete', board, method: :delete, data: { confirm: 'Are you sure?' } %>
																			<% end %>
																		</center>
															</div>
									    <% end %>
					</div><!-- end md 9 -->
								
</div><!-- end row -->


    

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<div class="row">
<div class="col-md-12">
 <h1><%= @board.board_name %></h1>
</div><!-- end md 4 -->
</div><!-- end row -->

<div class="row">
<div class="col-md-12" id="spacer"></div><!-- end md 4 -->
</div><!-- end row -->
<br />

<div class="row">
          <div class="col-md-2">
                        <h4>Surfboards</h4>
                        <% @boards.each do |board| %>
                        <%= link_to board.board_name, board %><br />
                        <% end %>
          </div><!-- end md 2 -->

          <div class="col-md-10">
            <div class="row">
                    <div class="col-md-5 text-left">
                              <% if @board.triimage.present? %>
                              <%= image_tag @board.triimage.url(:medium), class: "img-responsive" %>
                              <% end %>
                            </div><!-- end md 4 -->
                            <div class="col-md-7 text-left">
                                <br />
                                    <% if @board.logo.present? %>
                                    <%= image_tag @board.logo.url(:medium), class: "img-responsive" %>
                                <% end %>
                                <br />
                                <p><%= @board.board_description %></p>
                              
                                <center> 

                                   <% if @board.waveheightlogo.present? %>
                                    <h4>WAVE</h4>
                                   <%= image_tag @board.waveheightlogo.url(:medium), class: "img-responsive" %>
                                 <% end %>
                                 </center><br />
                                       <center>
                                        <% if @board.rockerlogo.present? %>
                                         <h4>SHAPE</h4>
                                        <%= image_tag @board.rockerlogo.url(:medium), class: "img-responsive" %>
                                        <% end %>
                                        </center><br />
                                              <center>
                                                 <% if @board.skilllogo.present? %>
                                                  <h4>SKILL LEVEL</h4>
                                                <%= image_tag @board.skilllogo.url(:medium), class: "img-responsive" %>
                                              <% end %>
                                              </center><br />
                                </div><!-- end md 4 -->
                        </div><!-- end row -->

            <div class="row">
                  <div class="col-md-4">
                    <h4>STANDARD DIMENSIONS</h4>
                        <table class="table table-condensed">
                                  <thead>
                                    <tr>
                                      <th>Length</th>
                                      <th>Width</th>
                                      <th>Thickness</th>
                                      <th>Volume</th>
                                      <th colspan="3"></th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    <% @board.dimensions.each do |dimension| %>
                                      <tr>
                                        <td><%= dimension.length %></td>
                                        <td><%= dimension.width %>"</td>
                                        <td><%= dimension.thickness %>"</td>
                                        <td><%= dimension.volume %>L</td>
                                        <td>
                                          <% if user_signed_in? %><%= link_to 'Edit', edit_dimension_path(dimension) %> &nbsp
                                        <%= link_to 'Delete', dimension, method: :delete, data: { confirm: 'Are you sure?' } %>
                                          <% end %>
                                      </td>
                                      </tr>
                                    <% end %>
                                  </tbody>
                                </table>
                  </div><!-- end md 4 -->
                  <div class="col-md-4"></div><!-- end md 4 -->
                  <div class="col-md-4"></div><!-- end md 4 -->
            </div><!-- end row -->


            </div><!-- end md 4 -->
            </div><!-- end row -->




<% if user_signed_in? %>
<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>
<% end %>




</div><!-- end md 4 -->
<div class="col-md-2"></div><!-- end md 4 -->
</div><!-- end row -->

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<% if user_signed_in? %>

<h1>Contacts (<%= Contact.count %>)</h1>
<%= link_to 'Create a New Contact', new_contact_path, class: "btn btn-default" %>
<table class="table table-responsive table-hover">
  <thead>
    <tr>
      <th>Created</th>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>How we can help</th>
      <th>Notes</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.created_at.to_formatted_s(:short) %></td>
        <td><%= contact.contact_name %></td>
        <td><%= contact.contact_email %></td>
        <td><%= contact.contact_phone %></td>
        <td><%= contact.contact_help %></td>
        <td><%= contact.contact_notes %></td>
        <td><%= contact.contact_status %></td>
      
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% else %>
YOU DO NOT HAVE PERMISSION TO ENTER THIS AREA 
<% end %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
<div class="col-md-12 text-center">

              <% if user_signed_in? %>
              <p>
                <strong>Contact name:</strong>
                <%= @contact.contact_name %>
              </p>

              <p>
                <strong>Contact email:</strong>
                <%= @contact.contact_email %>
              </p>

              <p>
                <strong>Contact phone:</strong>
                <%= @contact.contact_phone %>
              </p>

              <p>
                <strong>Contact help:</strong>
                <%= @contact.contact_help %>
              </p>

              <p>
                <strong>Contact notes:</strong>
                <%= @contact.contact_notes %>
              </p>

              <p>
                <strong>Contact status:</strong>
                <%= @contact.contact_status %>
              </p>



              <%= link_to 'Edit', edit_contact_path(@contact) %> |
              <%= link_to 'Back', contacts_path %>

<% else %> 
<h4>Thanks for contacting Diamond Surfboards.</h4>
<%= link_to "Go Back Home", root_path %>

<br /><br />
<% end %> 



</div><!-- end md 4 -->

</div><!-- end row -->

app/views/dimensions/edit.html.erb
<h1>Editing dimension</h1>

<%= render 'form' %>

<%= link_to 'Show', @dimension %> |
<%= link_to 'Back', dimensions_path %>

app/views/dimensions/index.html.erb
<h1>DIMENSIONS</h1>
<%= link_to 'New Dimension', new_dimension_path, class: "btn btn-default" %>
<table class="table">
  <thead>
    <tr>
      <th>Board</th>
      <th>Length</th>
      <th>Width</th>
      <th>Thickness</th>
      <th>Board</th>
      <th>Volume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dimensions.each do |dimension| %>
      <tr>
        <td><%= dimension.board.try(:board_name) %></td>
        <td><%= dimension.length %></td>
        <td><%= dimension.width %></td>
        <td><%= dimension.thickness %></td>
        <td><%= dimension.board_id %></td>
        <td><%= dimension.volume %></td>
        <td><%= link_to 'Show', dimension %></td>
        <td><%= link_to 'Edit', edit_dimension_path(dimension) %></td>
        <td><%= link_to 'Destroy', dimension, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/dimensions/new.html.erb
<div class="row">
<div class="col-md-3"></div><!-- end md 4 -->
<div class="col-md-6">

<h1>CREATE A NEW DIMENSION</h1>

<%= render 'form' %>

<%= link_to 'Back', dimensions_path %>


</div><!-- end md 4 -->
<div class="col-md-3"></div><!-- end md 4 -->
</div><!-- end row -->

app/views/dimensions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Length:</strong>
  <%= @dimension.length %>
</p>

<p>
  <strong>Width:</strong>
  <%= @dimension.width %>
</p>

<p>
  <strong>Thickness:</strong>
  <%= @dimension.thickness %>
</p>

<p>
  <strong>Board:</strong>
  <%= @dimension.board_id %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @dimension.volume %>
</p>

<%= link_to 'Edit', edit_dimension_path(@dimension) %> |
<%= link_to 'Back', dimensions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diamond Surfboards | Crafted in San Diego by Justin North</title>
  <meta name="description" content="Welcome to the Diamond Surfboards website. Diamond Surfboards are hand shaped by Justin North in Oceanside, California. Visit this site to learn more about Diamond Surfboards shapes, dimensions, and how you can order a board online.">
  <meta name="keywords" content="Diamond Surfboards, surfboards, surf, shortboard, shaper, oceanside, waves, living, fun">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>

<div class="container">




	<!-- temp sign in -->

				<div class="row" id="header">
						<div class="col-md-3 text-left">
							<%= link_to image_tag("https://s3.amazonaws.com/diamondsurfboards/images/diamondlogo.png", class: "img-responsive"), root_path %>
		     		</div><!-- end md 3 -->
     				<div class="col-md-9 text-right" id="headernav">
     								<%= link_to "HOME", root_path %> &nbsp; &nbsp;
     					<!-- 	<%= link_to "ABOUT", pages_diamond_path %> &nbsp; &nbsp; &nbsp; --> <%= link_to "SURFBOARDS", boards_path %> &nbsp; &nbsp; <!--
     						VOLUME CALCULATOR &nbsp; &nbsp; &nbsp; GEAR &nbsp; &nbsp; -->
     						<!-- sign in -->
                	<%= link_to "BLOG", blogs_path %> &nbsp; &nbsp;
     								<%= link_to "CONTACT", new_contact_path %> &nbsp; &nbsp;
     				</div>
				</div><!-- end row -->

				<div class="row">
						<div class="col-md-12">
								<% flash.each do |name, msg| %>
			     			<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
								<% end %>

								<%= yield %>


						</div><!-- end md 12 -->
				</div><!-- end row -->

<!-- end temp row -->

		<div class="row">
					<div class="col-md-12 text-center" id="footernav">
								<% if user_signed_in? %>
										<%= link_to "CONTACTS", contacts_path %> &nbsp; &nbsp; &nbsp;
										<%= link_to "DIMENSIONS", dimensions_path %> &nbsp; &nbsp; &nbsp;
										<%= link_to "USERS", pages_showusers_path %> &nbsp; &nbsp; &nbsp;
								<% end %>
<div class="row">
<div class="col-md-12 text-right" id="social">
<%= link_to "https://www.facebook.com/people/Diamond-Surfboards/100002396383191", target: "blank" do %><i class="fa fa-facebook fa-2x"></i><% end %>

</div><!-- end md 4 -->

</div><!-- end row -->

					</div><!-- end md 12 -->
		</div><!-- end row -->
		<div class="row" id="footernav">
							<div class="col-md-12 text-center" id="footer"><i class="fa fa-flag"></i> &nbsp; Made in Oceanside, California. &copy; 2015 DIAMOND SURFBOARDS. A <a href="http://www.nalumedia.com" target="new">NALU MEDIA</a> Project.

						<% if user_signed_in? %>
											<%= link_to current_user.email, edit_user_registration_path %> &nbsp; &nbsp; &nbsp;
											<%= link_to destroy_user_session_path, method: :delete do %>
													<i class="fa fa-sign-out"></i> Logout   &nbsp; &nbsp;
											<% end %>
											<% else %>
											<%=  link_to new_user_session_path do %>
								      Login  <% end %>
									<% end %>

							</div><!-- end md 12 -->
		</div><!-- end row -->
</div><!-- end container -->
<!-- analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64640980-1', 'auto');
  ga('send', 'pageview');
</script>
<!-- end analytics -->
</body>
</html>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<h1>SURFBOARDS</h1>
<div class="row">
<div class="col-md-12" id="spacer"></div><!-- end md 4 -->
</div><!-- end row -->
<br />

<% if user_signed_in? %>
<%= link_to 'Add a New Board', new_board_path, class: "btn btn-default" %> &nbsp; &nbsp; <%= link_to 'Add a New Board Type', new_type_path, class: "btn btn-default" %> <br /> <br />
<% end %>

<div class="row">
  <div class="col-md-12">
                  &nbsp; &nbsp; &nbsp; <%= link_to "> Sort By Board", boards_path %>
  </div>
</div>

<div class="row">
          <div class="col-md-12">
            <% @types.each do |type| %>       
                 <h2> <%= type.type_name %></h2>
                 <% if user_signed_in? %>
                                           <%= link_to 'View', type %> &nbsp; &nbsp; <%= link_to 'Edit', edit_type_path(type) %>&nbsp; &nbsp;
                                             <%= link_to 'Delete', type, method: :delete, data: { confirm: 'Are you sure?' } %>
                                      <% end %>

                  <ul class="products">
                      <li>
                  <% type.boards.each do |board| %>
          
                              <div class="listing">
                                    <center>
                                    <b><%= link_to board.board_name, board %></b><br />
                                          <%= link_to image_tag(board.image.url(:medium), class: "img-responsive"), board %><br />
                                                  <% if user_signed_in? %>
                                           <%= link_to 'View', board %> &nbsp; &nbsp; <%= link_to 'Edit', edit_board_path(board) %>&nbsp; &nbsp;
                                             <%= link_to 'Delete', board, method: :delete, data: { confirm: 'Are you sure?' } %>
                                      <% end %>
                                    </center>
                              </div> <!-- end listing -->
                        </li>
                    <% end %> <!-- end board --> 
                  </ul>
                 
             <% end %><!-- end types -->
  
          </div><!-- end md 12 -->
                
</div><!-- end row -->

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type name:</strong>
  <%= @type.type_name %>
</p>

<p>
  <strong>Type description:</strong>
  <%= @type.type_description %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>